### ISSUE TITLE
off-by-one error in maximum lease length calculation in client stub

### ISSUE THREAD

**Issue by bcantrill** [oxidecomputer/idolatry#1]
In the client stub, the size calculation is off-by-one:

https://github.com/oxidecomputer/idolatry/blob/ec1047cce1c35dad72162b102e9a8193f0f4572d/src/client.rs#L134

This (incorrectly) panics if the length is equal to the maximum allowed length; the check should be `>`, not `>=`.

**Comment by cbiffle** [comment]
Good catch.
