### ISSUE TITLE
duplicate operations, arguments, and leases are allowed

### ISSUE THREAD

**Issue by bcantrill** [oxidecomputer/idolatry#9]
Through a mismerge in an Idol file, I (accidentally) discovered that the Idolatry allowed duplicate operations and arguments. On the one hand, this is not surprising, as it is Serde's default behavior (with the last key winning), but it would also be be nice to prevent this -- this is certainly an error in the Idol file, and it can be hard to debug. Unfortunately, the normal mechanism for doing this -- namely. use `serde_with` and then the `#[serde(with = "serde_with::rust::maps_duplicate_key_is_error")]` annotation -- doesn't work for IndexMap. This calls for more Serde-fu than I currently possess!

**Comment by cbiffle** [comment]
Huh, `duplicate_key_is_error` not working for `IndexMap` is disappointing. I'll look into alternatives there.
